# Generated by Django 5.1.4 on 2024-12-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.TextField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
